
spring:
  application:
    name: mall-admin-springboot01
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
#
management:
  endpoint:
    health:
      show-details: always
 server:
   port: 9091
 endpoints:
   web:
       exposure:
         include: ["health","info","env","metrics","beans"]
server:
  port: 8081

